version: "3.4"
services:
  vite_docker:
    image: node:alpine
    container_name: vite_docker
    entrypoint: /bin/sh
    ports:
      - 4173:4173
    working_dir: /app
    environment:
      - VITE_APOLLO_CLIENT_URL=${VITE_APOLLO_CLIENT_URL}
    volumes:
      - type: bind
        source: ./ui
        target: /app
    tty: true
